version: '3'

networks:
  main:
    driver: bridge
  kong:
    driver: bridge
  accounts:
    driver: bridge

volumes:
  kong_db_data:
  accounts_db_data:

services:
  gateway-database:
    image: postgres:15.4-alpine3.18
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong
      - POSTGRES_PASSWORD=kong
    volumes:
      - kong_db_data:/var/lib/postgresql/data
    networks:
      - kong
  api-gateway:
    image: kong/kong-gateway:3.2-alpine
    volumes:
      - ./kong.yml:/usr/local/kong/declarative/kong.yml
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=gateway-database
      - KONG_LOG_LEVEL=info
      - KONG_PG_USER=kong
      - KONG_PG_PASSWORD=kong
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
      - KONG_ADMIN_GUI_URL=http://localhost:8002
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8002:8002"
      - "127.0.0.1:8001:8001"
      - "127.0.0.1:8444:8444"
    depends_on:
      - gateway-database
    networks:
      - kong
      - main
  accounts-database:
    image: postgres:15.4-alpine3.18
    environment:
      - POSTGRES_DB=accountsdb
      - POSTGRES_USER=accounts_admin
      - POSTGRES_PASSWORD=accounts
    volumes:
      - accounts_db_data:/var/lib/postgresql/data
    networks:
      - accounts
  accounts-service:
    build: ./services/account-service
    image: canela/accounts
    environment:
      - SERVER_PORT=8081
      - DATABASE_USER=accounts_admin
      - DATABASE_PASSWORD=accounts
      - DATABASE_URL=jdbc:postgresql://accounts-database:5432/accountsdb
      - HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
      - HIBERNATE_DDL_AUTO=update
    depends_on:
      - accounts-database
    networks:
      - accounts
      - main
